export const EVENT_ITEM_LIST_SUCCESS = 'EVENT_ITEM_LIST_SUCCESS';
export const EVENT_ITEM_LIST_REQUEST = 'EVENT_ITEM_LIST_REQUEST';
export const EVENT_ITEM_LIST_FAIL = 'EVENT_ITEM_LIST_FAIL';

export const EVENT_ITEM_DETAILS_SUCCESS = 'EVENT_ITEM_DETAILS_SUCCESS';
export const EVENT_ITEM_DETAILS_REQUEST = 'EVENT_ITEM_DETAILS_REQUEST';
export const EVENT_ITEM_DETAILS_FAIL = 'EVENT_ITEM_DETAILS_FAIL';
export const EVENT_ITEM_DETAILS_RESET = 'EVENT_ITEM_DETAILS_RESET';

export const EVENT_ITEM_DELETE_REQUEST = 'EVENT_ITEM_DELETE_REQUEST';
export const EVENT_ITEM_DELETE_SUCCESS = 'EVENT_ITEM_DELETE_SUCCESS';
export const EVENT_ITEM_DELETE_FAIL = 'EVENT_ITEM_DELETE_FAIL';

export const EVENT_ITEM_UPDATE_REQUEST = 'EVENT_ITEM_UPDATE_REQUEST';
export const EVENT_ITEM_UPDATE_SUCCESS = 'EVENT_ITEM_UPDATE_SUCCESS';
export const EVENT_ITEM_UPDATE_FAIL = 'EVENT_ITEM_UPDATE_FAIL';
export const EVENT_ITEM_UPDATE_PROFILE_RESET = 'EVENT_ITEM_UPDATE_PROFILE_RESET';
export const EVENT_ITEM_UPDATE_RESET = 'EVENT_ITEM_UPDATE_RESET';

export const EVENT_ITEM_CREATE_REQUEST = 'EVENT_ITEM_CREATE_REQUEST';
export const EVENT_ITEM_CREATE_SUCCESS = 'EVENT_ITEM_CREATE_SUCCESS';
export const EVENT_ITEM_CREATE_FAIL = 'EVENT_ITEM_CREATE_FAIL';
export const EVENT_ITEM_CREATE_PROFILE_RESET = 'EVENT_ITEM_CREATE_PROFILE_RESET';
export const EVENT_ITEM_CREATE_RESET = 'EVENT_ITEM_CREATE_RESET';
